apiVersion: apps/v1
kind: Deployment
metadata:
  name: buscacapitaldeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buscacapital
  template:
    metadata:
      labels:
        app: buscacapital
    spec:
      containers:
        - name: buscacapital
          image: lufertony/buscacapital:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: busca-service
spec:
  selector:
    app: buscacapital
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
      nodePort: 30000
  
